global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "ten-gnn-api"
    static_configs:
      - targets: ["ten-gnn-cpu:8000", "ten-gnn-gpu:8000"]
    metrics_path: "/metrics"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
